# Generated by Django 6.0.4 on 2026-05-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregestration',
            old_name='username',
            new_name='fullname',
        ),
    ]
