# Generated by Django 6.0.4 on 2026-05-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_username_userregestration_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegestration',
        ),
    ]
