# Generated by Django 6.0.4 on 2026-04-29 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_remove_createtask_due_date_alter_createtask_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtask',
            name='due_date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
    ]
