# Generated by Django 6.0.4 on 2026-05-02 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_createtask_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtask',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_app.board'),
        ),
    ]
