# Generated by Django 6.0.4 on 2026-05-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_board_members'),
        ('task_app', '0004_alter_createtask_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtask',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board_app.board'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
