# Generated by Django 6.0.4 on 2026-05-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_remove_createtask_assignee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task_app.createtask'),
        ),
    ]
