# Generated by Django 6.0.4 on 2026-05-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0007_alter_comments_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createtask',
            old_name='assignee_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='createtask',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
