# Generated by Django 6.0.4 on 2026-05-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_rename_assignee_id_createtask_assignee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createtask',
            old_name='assignee',
            new_name='assignee_id',
        ),
        migrations.RenameField(
            model_name='createtask',
            old_name='reviewer',
            new_name='reviewer_id',
        ),
    ]
